<a href="https://colab.research.google.com/github/Sudharshana-HG/DSFEB12/blob/main/python_day_1_feb_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("My Name is Brad")

My Name is Brad


In [ ]:
# COMMENT
# Enter - It goes to next line within same code block
# Shift + Enter - It executes this code block and goes to next code block
# Alt + Enter - It executes this code block and creates a new code block
# Ctrl + Enter - It executes this code block

In [ ]:
#TYPES OF BRACKETS
#[] - data extraction/slicing of data, lists
#{}  - dictionaries/sets
#() - methods/functions, tuples

In [ ]:
x = 20

In [ ]:
x

20

In [ ]:
type(x)

int

In [ ]:
y = 'brad'
type(y)

str

In [ ]:
z = 13.5
type(z)

float

In [ ]:
a = True
type(a)

bool

In [ ]:
#DATA TYPES 
#string - character or alphabet
#float - decimal 
#integer - number
#boolean - logical - True or False


In [ ]:
print(20+10)
print(100-80)
print(990/99)
print(85*10)

30
20
10.0
850


In [ ]:
import math

In [ ]:
math.sqrt(64)

8.0

In [ ]:
list1 = ["Brad", 20, 13.5, True]

In [ ]:
list1

['Brad', 20, 13.5, True]

In [ ]:
#Index in Python starts with 0 

In [ ]:
list1[1] 

20

In [ ]:
list1[1] = 40
list1

['Brad', 40, 13.5, True]

In [ ]:
test =4>1

In [ ]:
test

True

In [ ]:
type(test)

bool

In [ ]:
sample=7>6

In [ ]:
sample2=6>8

In [ ]:
sample and sample2

False

In [ ]:
sample3 =5>1

In [ ]:
sample4 =6>3

In [ ]:
sample3 and sample4

True

In [ ]:
i=0
while i <=10:
  print(i)
  i=i+1
print('python is good')

0
1
2
3
4
5
6
7
8
9
10
python is good


In [ ]:
range(6)

range(0, 6)

In [ ]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [ ]:
#Indexing starts from 0 and endind with last value -1

In [ ]:
for i in   range(6):
  print(i)

0
1
2
3
4
5


In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
result = None
x = randn()
if x>1:
  result="greater than 1"
print(x)
print(result)

1.0172483896311049
greater than 1


In [ ]:
result = None
x = randn()
if x>1:
  result="greater than 1"
elif x <-1:
  result ="less than -1"
else:
  result  ="between -1  and 1"
print(x)
print(result)

-0.11328177041686273
between -1  and 1


In [ ]:
list1=[1,2,3,4,5,6]
list1

[1, 2, 3, 4, 5, 6]

In [ ]:
type(list1)

list

In [ ]:
list(range(1,51,3))

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]

In [ ]:
list2=list(range(1,51,3))

In [ ]:
list2[1]

4

In [ ]:
letter=['a','b','c','d','e','f','h','i']
letter

['a', 'b', 'c', 'd', 'e', 'f', 'h', 'i']

In [ ]:
letter[1:8:2]

['b', 'd', 'f', 'i']

In [ ]:
letter[-9:-1:2]

['a', 'c', 'e', 'h']

In [ ]:
letter[1::2]

['b', 'd', 'f', 'i']

In [ ]:
letter[::3]

['a', 'd', 'h']

In [ ]:
letter[:7]

['a', 'b', 'c', 'd', 'e', 'f', 'h']

In [ ]:
letter[7:]

['i']

In [ ]:
letter[::-1]

['i', 'h', 'f', 'e', 'd', 'c', 'b', 'a']

In [ ]:
tuple1=(12,6,72)


In [ ]:
tuple1[1]

6

In [ ]:
len(list1)

6

In [ ]:
max(list1)

6

In [ ]:
min(list1)

1

In [ ]:
import numpy as np

In [ ]:
lists=['a',20,30.5,True]

In [ ]:
np.array(lists)

array(['a', '20', '30.5', 'True'], dtype='<U32')

In [ ]:
list6=[20,50.5,20,True]
np.array(list6)

array([20. , 50.5, 20. ,  1. ])

In [ ]:
b=np.array([1234,6789,9876,1456,-1234])

In [ ]:
b.mean()

3624.2

In [ ]:
b

array([ 1234,  6789,  9876,  1456, -1234])

In [ ]:
b[::2]

array([ 1234,  9876, -1234])

In [ ]:
b[1::2]

array([6789, 1456])

In [ ]:
c=b[2:4]

In [ ]:
c

array([9876, 1456])

In [ ]:
b

array([ 1234,  6789,  9876,  1456, -1234])

In [ ]:
#dictionary

In [ ]:
dict1={'Index@':'emp NO','Index1':'emp name','Index2':'salary'}

In [ ]:
dict1

{'Index@': 'emp NO', 'Index1': 'emp name', 'Index2': 'salary'}

In [ ]:
dict1['Index1']

'emp name'